### ISSUE TITLE
Flood fill function

### ISSUE THREAD

**Issue by DjPoke** [AgonConsole8/agon-bbc-basic#4]
Hi,
Flood fill is not implemented in BBC BASIC, for now, but is it implemented in the VDU ?

**Comment by stevesims** [comment]
No.

flood fill has never been a language feature of any version of BBC BASIC. It was supported via VDU calls, which on the Agon architecture are exclusively the domain of the VDP.

At this time the VDP cannot support any of the VDU fill operations, including but not limited to flood fill. At some point in the future this _may_ change, at which point the VDU operation would just work in BASIC with no changes needed.
